### ISSUE TITLE
Icons missing from tool bar

### ISSUE THREAD

**Issue by drdan18** [AlexNewson/tool-bar-basic#5]
The Fold All and Unfold All icons are blank in the tool-bar.  This happened after an update was received.  I am not sure if the update was for this package or a different one.

**Comment by AlexNewson** [comment]
I'm pretty sure this was when tool-bar updated to using Font Awesome 5.4.2 in v1.1.11 (https://github.com/suda/tool-bar/pull/249)

I'll try and get a fix out today

**Comment by drdan18** [comment]
Thanks.

**Comment by AlexNewson** [comment]
All fixed, package should be updated to Font Awesome 5

**Comment by absmith82** [comment]
Some of the tool-bar icons are missing again.  I manually changed them in my settings so that I had some icons but I'm unsure what the defaults are supposed to be just wanted to let you know it is happening
